name: RSOLV Automated Fix

on:
  issues:
    types: [opened, labeled]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to fix'
        required: false
        type: string

jobs:
  automated-fix:
    # Only run if the issue has the rsolv:automate label
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'rsolv:automate')) ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run RSOLV Mitigation
        uses: rsolv-dev/rsolv-action@main
        with:
          rsolvApiKey: ${{ secrets.RSOLV_API_KEY }}
          mode: 'mitigate'
          issue_number: ${{ github.event.issue.number || github.event.inputs.issue_number }}
          enable_security_analysis: 'true'
          enable_ast_validation: 'true'
          use_git_based_editing: 'true'
          use_structured_phases: 'true'
          enable_educational_pr: 'true'
          disable_fix_validation: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}